version: '3.1'

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    build: .
    restart: always
    ports:
      - 8059:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: "${DB_USER:?O usuário da DB não foi definido}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:?A senha da DB não foi definida}"
      WORDPRESS_DB_NAME: "${DB_DATABASE:?Nome da DB não foi definida}"
  #    volumes:
  #      - ./public:/opt/web/public
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:?Nome da DB não foi definida}"
      MYSQL_USER: "${DB_USER:?O usuário da DB não foi definido}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?A senha da DB não foi definida}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: